export const createRegistryApi = (legacyApi) => ({
    getBuildings: legacyApi.getBuildings,
    createBuilding: legacyApi.createBuilding,
    updateBuilding: legacyApi.updateBuilding,
    deleteBuilding: legacyApi.deleteBuilding,
    getFloors: legacyApi.getFloors,
    updateFloor: legacyApi.updateFloor,
    generateFloors: legacyApi.generateFloors,
    getEntrances: legacyApi.getEntrances,
    getMatrix: legacyApi.getMatrix,
    upsertMatrixCell: legacyApi.upsertMatrixCell,
    syncEntrances: legacyApi.syncEntrances,
    getUnits: legacyApi.getUnits,
    upsertUnit: legacyApi.upsertUnit,
    batchUpsertUnits: legacyApi.batchUpsertUnits,
    getCommonAreas: legacyApi.getCommonAreas,
    upsertCommonArea: legacyApi.upsertCommonArea,
    deleteCommonArea: legacyApi.deleteCommonArea,
    clearCommonAreas: legacyApi.clearCommonAreas,
    getBasements: legacyApi.getBasements,
    toggleBasementLevel: legacyApi.toggleBasementLevel,
    getParkingCounts: legacyApi.getParkingCounts,
    syncParkingPlaces: legacyApi.syncParkingPlaces
});
