import { ROLES } from '../../lib/constants.js';

export const DASHBOARD_DECLINE_SUBSTATUS = {
  ADMIN: 'DECLINED_BY_ADMIN',
  CONTROLLER: 'DECLINED_BY_CONTROLLER',
  BRANCH_MANAGER: 'DECLINED_BY_MANAGER',
};

export const getDeclineSubstatusByRole = role => {
  if (role === ROLES.BRANCH_MANAGER) return DASHBOARD_DECLINE_SUBSTATUS.BRANCH_MANAGER;
  if (role === ROLES.CONTROLLER) return DASHBOARD_DECLINE_SUBSTATUS.CONTROLLER;
  return DASHBOARD_DECLINE_SUBSTATUS.ADMIN;
};
