spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:postgresql://192.168.112.48:5432/mkd"
    username: "postgres"
    password: "migration@2hE&z53P43Q"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        "[highlight_sql]": true

logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.orm.jdbc.bind]": TRACE
    "[org.springframework.jdbc.core]": DEBUG

app:
  jwt-secret: "my_super_secret_dev_key_12345!@#"
